/**
 * Copies Font Awesome out of node_modules into `src/renderer/vendor/` so the
 * renderer can load it with a 'self'-only CSP and work offline.
 */
const fs = require("fs");
const path = require("path");

const projectRoot = path.join(__dirname, "..");
const vendorRoot = path.join(projectRoot, "src", "renderer", "vendor");

const FILES = [
    ["@fortawesome/fontawesome-free/css/all.min.css", "fontawesome/css/all.min.css"],
    ["@fortawesome/fontawesome-free/webfonts/fa-solid-900.woff2", "fontawesome/webfonts/fa-solid-900.woff2"],
    ["@fortawesome/fontawesome-free/webfonts/fa-solid-900.ttf", "fontawesome/webfonts/fa-solid-900.ttf"],
    ["@fortawesome/fontawesome-free/webfonts/fa-regular-400.woff2", "fontawesome/webfonts/fa-regular-400.woff2"],
    ["@fortawesome/fontawesome-free/webfonts/fa-regular-400.ttf", "fontawesome/webfonts/fa-regular-400.ttf"],
    ["@fortawesome/fontawesome-free/webfonts/fa-brands-400.woff2", "fontawesome/webfonts/fa-brands-400.woff2"],
    ["@fortawesome/fontawesome-free/webfonts/fa-brands-400.ttf", "fontawesome/webfonts/fa-brands-400.ttf"],
    ["@fortawesome/fontawesome-free/webfonts/fa-v4compatibility.woff2", "fontawesome/webfonts/fa-v4compatibility.woff2"],
    ["@fortawesome/fontawesome-free/webfonts/fa-v4compatibility.ttf", "fontawesome/webfonts/fa-v4compatibility.ttf"]
];

function copy(relativeSource, relativeDest) {
    const source = path.join(projectRoot, "node_modules", relativeSource);
    if (!fs.existsSync(source)) {
        throw new Error(`Missing vendor source: node_modules/${relativeSource} — run npm install first.`);
    }
    const dest = path.join(vendorRoot, relativeDest);
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(source, dest);
    return dest;
}

function main() {
    fs.rmSync(vendorRoot, { recursive: true, force: true });
    const copied = FILES.map(([from, to]) => {
        copy(from, to);
        return to;
    });

    fs.writeFileSync(
        path.join(vendorRoot, "README.md"),
        [
            "# Vendored browser assets",
            "",
            "Generated by `npm run sync:vendor` — do not edit by hand.",
            "",
            ...copied.map((file) => `- \`${file}\``),
            ""
        ].join("\n"),
        "utf8"
    );

    console.log(`Vendored ${copied.length} files into src/renderer/vendor/`);
}

main();
